export enum ThemeColorVar {
    WHITE = "--c-white",
    RED = "--c-red",
    PINK = "--c-pink",
    PURPLE = "--c-purple",
    DEEP_PURPLE = "--c-deep-purple",
    INDIGO = "--c-indigo",
    BLUE = "--c-blue",
    LIGHT_BLUE = "--c-light-blue",
    CYAN = "--c-cyan",
    TEAL = "--c-teal",
    GREEN = "--c-green",
    LIGHT_GREEN = "--c-light-green",
    LIME = "--c-lime",
    YELLOW = "--c-yellow",
    AMBER = "--c-amber",
    ORANGE = "--c-orange",
    DEEP_ORANGE = "--c-deep-orange",
    BROWN = "--c-brown",
    GRAY = "--c-gray",
    BLUE_GRAY = "--c-blue-gray",
    BLACK = "--c-black",
}